# Generated by proofs/json_to_python.py from a Rocq JSON extraction. Do not edit by hand.
# Every function below is the structural image of the verified MiniML source.

def app(l):
    def _k(m):
        _t1 = l
        if _t1[0] == 'Nil':
            return m
        elif _t1[0] == 'Cons':
            a = _t1[1]
            l1 = _t1[2]
            return ('Cons', a, app(l1)(m))
    return _k

def join(a):
    def _k(b):
        _t2 = a
        if _t2[0] == 'Some':
            la = _t2[1]
            _t3 = b
            if _t3[0] == 'Some':
                lb = _t3[1]
                return ('Some', app(la)(lb))
            elif _t3[0] == 'None':
                return ('None',)
        elif _t2[0] == 'None':
            return ('None',)
    return _k
