# Generated by proofs/json_to_python.py from a Rocq JSON extraction. Do not edit by hand.
# Every function below is the structural image of the verified MiniML source.

def negb(b):
    _t1 = b
    if _t1[0] == 'True':
        return ('False',)
    elif _t1[0] == 'False':
        return ('True',)

def compOpp(r):
    _t2 = r
    if _t2[0] == 'Eq':
        return ('Eq',)
    elif _t2[0] == 'Lt':
        return ('Gt',)
    elif _t2[0] == 'Gt':
        return ('Lt',)

def succ(x):
    _t3 = x
    if _t3[0] == 'XI':
        p = _t3[1]
        return ('XO', succ(p))
    elif _t3[0] == 'XO':
        p = _t3[1]
        return ('XI', p)
    elif _t3[0] == 'XH':
        return ('XO', ('XH',))

def add(x):
    def _k(y):
        _t4 = x
        if _t4[0] == 'XI':
            p = _t4[1]
            _t5 = y
            if _t5[0] == 'XI':
                q = _t5[1]
                return ('XO', add_carry(p)(q))
            elif _t5[0] == 'XO':
                q = _t5[1]
                return ('XI', add(p)(q))
            elif _t5[0] == 'XH':
                return ('XO', succ(p))
        elif _t4[0] == 'XO':
            p = _t4[1]
            _t6 = y
            if _t6[0] == 'XI':
                q = _t6[1]
                return ('XI', add(p)(q))
            elif _t6[0] == 'XO':
                q = _t6[1]
                return ('XO', add(p)(q))
            elif _t6[0] == 'XH':
                return ('XI', p)
        elif _t4[0] == 'XH':
            _t7 = y
            if _t7[0] == 'XI':
                q = _t7[1]
                return ('XO', succ(q))
            elif _t7[0] == 'XO':
                q = _t7[1]
                return ('XI', q)
            elif _t7[0] == 'XH':
                return ('XO', ('XH',))
    return _k

def add_carry(x):
    def _k(y):
        _t8 = x
        if _t8[0] == 'XI':
            p = _t8[1]
            _t9 = y
            if _t9[0] == 'XI':
                q = _t9[1]
                return ('XI', add_carry(p)(q))
            elif _t9[0] == 'XO':
                q = _t9[1]
                return ('XO', add_carry(p)(q))
            elif _t9[0] == 'XH':
                return ('XI', succ(p))
        elif _t8[0] == 'XO':
            p = _t8[1]
            _t10 = y
            if _t10[0] == 'XI':
                q = _t10[1]
                return ('XO', add_carry(p)(q))
            elif _t10[0] == 'XO':
                q = _t10[1]
                return ('XI', add(p)(q))
            elif _t10[0] == 'XH':
                return ('XO', succ(p))
        elif _t8[0] == 'XH':
            _t11 = y
            if _t11[0] == 'XI':
                q = _t11[1]
                return ('XI', succ(q))
            elif _t11[0] == 'XO':
                q = _t11[1]
                return ('XO', succ(q))
            elif _t11[0] == 'XH':
                return ('XI', ('XH',))
    return _k

def pred_double(x):
    _t12 = x
    if _t12[0] == 'XI':
        p = _t12[1]
        return ('XI', ('XO', p))
    elif _t12[0] == 'XO':
        p = _t12[1]
        return ('XI', pred_double(p))
    elif _t12[0] == 'XH':
        return ('XH',)

def mul(x):
    def _k(y):
        _t13 = x
        if _t13[0] == 'XI':
            p = _t13[1]
            return add(y)(('XO', mul(p)(y)))
        elif _t13[0] == 'XO':
            p = _t13[1]
            return ('XO', mul(p)(y))
        elif _t13[0] == 'XH':
            return y
    return _k

def compare_cont(r):
    def _k(x):
        def _k(y):
            _t14 = x
            if _t14[0] == 'XI':
                p = _t14[1]
                _t15 = y
                if _t15[0] == 'XI':
                    q = _t15[1]
                    return compare_cont(r)(p)(q)
                elif _t15[0] == 'XO':
                    q = _t15[1]
                    return compare_cont(('Gt',))(p)(q)
                elif _t15[0] == 'XH':
                    return ('Gt',)
            elif _t14[0] == 'XO':
                p = _t14[1]
                _t16 = y
                if _t16[0] == 'XI':
                    q = _t16[1]
                    return compare_cont(('Lt',))(p)(q)
                elif _t16[0] == 'XO':
                    q = _t16[1]
                    return compare_cont(r)(p)(q)
                elif _t16[0] == 'XH':
                    return ('Gt',)
            elif _t14[0] == 'XH':
                _t17 = y
                if _t17[0] == 'XH':
                    return r
                else:
                    return ('Lt',)
        return _k
    return _k

compare = compare_cont(('Eq',))

def eqb(p):
    def _k(q):
        _t18 = p
        if _t18[0] == 'XI':
            p0 = _t18[1]
            _t19 = q
            if _t19[0] == 'XI':
                q0 = _t19[1]
                return eqb(p0)(q0)
            else:
                return ('False',)
        elif _t18[0] == 'XO':
            p0 = _t18[1]
            _t20 = q
            if _t20[0] == 'XO':
                q0 = _t20[1]
                return eqb(p0)(q0)
            else:
                return ('False',)
        elif _t18[0] == 'XH':
            _t21 = q
            if _t21[0] == 'XH':
                return ('True',)
            else:
                return ('False',)
    return _k

def double(x):
    _t22 = x
    if _t22[0] == 'Z0':
        return ('Z0',)
    elif _t22[0] == 'Zpos':
        p = _t22[1]
        return ('Zpos', ('XO', p))
    elif _t22[0] == 'Zneg':
        p = _t22[1]
        return ('Zneg', ('XO', p))

def succ_double(x):
    _t23 = x
    if _t23[0] == 'Z0':
        return ('Zpos', ('XH',))
    elif _t23[0] == 'Zpos':
        p = _t23[1]
        return ('Zpos', ('XI', p))
    elif _t23[0] == 'Zneg':
        p = _t23[1]
        return ('Zneg', pred_double(p))

def pred_double0(x):
    _t24 = x
    if _t24[0] == 'Z0':
        return ('Zneg', ('XH',))
    elif _t24[0] == 'Zpos':
        p = _t24[1]
        return ('Zpos', pred_double(p))
    elif _t24[0] == 'Zneg':
        p = _t24[1]
        return ('Zneg', ('XI', p))

def pos_sub(x):
    def _k(y):
        _t25 = x
        if _t25[0] == 'XI':
            p = _t25[1]
            _t26 = y
            if _t26[0] == 'XI':
                q = _t26[1]
                return double(pos_sub(p)(q))
            elif _t26[0] == 'XO':
                q = _t26[1]
                return succ_double(pos_sub(p)(q))
            elif _t26[0] == 'XH':
                return ('Zpos', ('XO', p))
        elif _t25[0] == 'XO':
            p = _t25[1]
            _t27 = y
            if _t27[0] == 'XI':
                q = _t27[1]
                return pred_double0(pos_sub(p)(q))
            elif _t27[0] == 'XO':
                q = _t27[1]
                return double(pos_sub(p)(q))
            elif _t27[0] == 'XH':
                return ('Zpos', pred_double(p))
        elif _t25[0] == 'XH':
            _t28 = y
            if _t28[0] == 'XI':
                q = _t28[1]
                return ('Zneg', ('XO', q))
            elif _t28[0] == 'XO':
                q = _t28[1]
                return ('Zneg', pred_double(q))
            elif _t28[0] == 'XH':
                return ('Z0',)
    return _k

def add0(x):
    def _k(y):
        _t29 = x
        if _t29[0] == 'Z0':
            return y
        elif _t29[0] == 'Zpos':
            x_prime = _t29[1]
            _t30 = y
            if _t30[0] == 'Z0':
                return x
            elif _t30[0] == 'Zpos':
                y_prime = _t30[1]
                return ('Zpos', add(x_prime)(y_prime))
            elif _t30[0] == 'Zneg':
                y_prime = _t30[1]
                return pos_sub(x_prime)(y_prime)
        elif _t29[0] == 'Zneg':
            x_prime = _t29[1]
            _t31 = y
            if _t31[0] == 'Z0':
                return x
            elif _t31[0] == 'Zpos':
                y_prime = _t31[1]
                return pos_sub(y_prime)(x_prime)
            elif _t31[0] == 'Zneg':
                y_prime = _t31[1]
                return ('Zneg', add(x_prime)(y_prime))
    return _k

def opp(x):
    _t32 = x
    if _t32[0] == 'Z0':
        return ('Z0',)
    elif _t32[0] == 'Zpos':
        x0 = _t32[1]
        return ('Zneg', x0)
    elif _t32[0] == 'Zneg':
        x0 = _t32[1]
        return ('Zpos', x0)

def sub(m):
    def _k(n):
        return add0(m)(opp(n))
    return _k

def mul0(x):
    def _k(y):
        _t33 = x
        if _t33[0] == 'Z0':
            return ('Z0',)
        elif _t33[0] == 'Zpos':
            x_prime = _t33[1]
            _t34 = y
            if _t34[0] == 'Z0':
                return ('Z0',)
            elif _t34[0] == 'Zpos':
                y_prime = _t34[1]
                return ('Zpos', mul(x_prime)(y_prime))
            elif _t34[0] == 'Zneg':
                y_prime = _t34[1]
                return ('Zneg', mul(x_prime)(y_prime))
        elif _t33[0] == 'Zneg':
            x_prime = _t33[1]
            _t35 = y
            if _t35[0] == 'Z0':
                return ('Z0',)
            elif _t35[0] == 'Zpos':
                y_prime = _t35[1]
                return ('Zneg', mul(x_prime)(y_prime))
            elif _t35[0] == 'Zneg':
                y_prime = _t35[1]
                return ('Zpos', mul(x_prime)(y_prime))
    return _k

def compare0(x):
    def _k(y):
        _t36 = x
        if _t36[0] == 'Z0':
            _t37 = y
            if _t37[0] == 'Z0':
                return ('Eq',)
            elif _t37[0] == 'Zpos':
                return ('Lt',)
            elif _t37[0] == 'Zneg':
                return ('Gt',)
        elif _t36[0] == 'Zpos':
            x_prime = _t36[1]
            _t38 = y
            if _t38[0] == 'Zpos':
                y_prime = _t38[1]
                return compare(x_prime)(y_prime)
            else:
                return ('Gt',)
        elif _t36[0] == 'Zneg':
            x_prime = _t36[1]
            _t39 = y
            if _t39[0] == 'Zneg':
                y_prime = _t39[1]
                return compOpp(compare(x_prime)(y_prime))
            else:
                return ('Lt',)
    return _k

def leb(x):
    def _k(y):
        _t40 = compare0(x)(y)
        if _t40[0] == 'Gt':
            return ('False',)
        else:
            return ('True',)
    return _k

def ltb(x):
    def _k(y):
        _t41 = compare0(x)(y)
        if _t41[0] == 'Lt':
            return ('True',)
        else:
            return ('False',)
    return _k

def eqb0(x):
    def _k(y):
        _t42 = x
        if _t42[0] == 'Z0':
            _t43 = y
            if _t43[0] == 'Z0':
                return ('True',)
            else:
                return ('False',)
        elif _t42[0] == 'Zpos':
            p = _t42[1]
            _t44 = y
            if _t44[0] == 'Zpos':
                q = _t44[1]
                return eqb(p)(q)
            else:
                return ('False',)
        elif _t42[0] == 'Zneg':
            p = _t42[1]
            _t45 = y
            if _t45[0] == 'Zneg':
                q = _t45[1]
                return eqb(p)(q)
            else:
                return ('False',)
    return _k

def pos_div_eucl(a):
    def _k(b):
        _t46 = a
        if _t46[0] == 'XI':
            a_prime = _t46[1]
            _t47 = pos_div_eucl(a_prime)(b)
            if _t47[0] == 'Pair':
                q = _t47[1]
                r = _t47[2]
                r_prime = add0(mul0(('Zpos', ('XO', ('XH',))))(r))(('Zpos', ('XH',)))
                _t48 = ltb(r_prime)(b)
                if _t48[0] == 'True':
                    return ('Pair', mul0(('Zpos', ('XO', ('XH',))))(q), r_prime)
                elif _t48[0] == 'False':
                    return ('Pair', add0(mul0(('Zpos', ('XO', ('XH',))))(q))(('Zpos', ('XH',))), sub(r_prime)(b))
        elif _t46[0] == 'XO':
            a_prime = _t46[1]
            _t49 = pos_div_eucl(a_prime)(b)
            if _t49[0] == 'Pair':
                q = _t49[1]
                r = _t49[2]
                r_prime = mul0(('Zpos', ('XO', ('XH',))))(r)
                _t50 = ltb(r_prime)(b)
                if _t50[0] == 'True':
                    return ('Pair', mul0(('Zpos', ('XO', ('XH',))))(q), r_prime)
                elif _t50[0] == 'False':
                    return ('Pair', add0(mul0(('Zpos', ('XO', ('XH',))))(q))(('Zpos', ('XH',))), sub(r_prime)(b))
        elif _t46[0] == 'XH':
            _t51 = leb(('Zpos', ('XO', ('XH',))))(b)
            if _t51[0] == 'True':
                return ('Pair', ('Z0',), ('Zpos', ('XH',)))
            elif _t51[0] == 'False':
                return ('Pair', ('Zpos', ('XH',)), ('Z0',))
    return _k

def div_eucl(a):
    def _k(b):
        _t52 = a
        if _t52[0] == 'Z0':
            return ('Pair', ('Z0',), ('Z0',))
        elif _t52[0] == 'Zpos':
            a_prime = _t52[1]
            _t53 = b
            if _t53[0] == 'Z0':
                return ('Pair', ('Z0',), a)
            elif _t53[0] == 'Zpos':
                return pos_div_eucl(a_prime)(b)
            elif _t53[0] == 'Zneg':
                b_prime = _t53[1]
                _t54 = pos_div_eucl(a_prime)(('Zpos', b_prime))
                if _t54[0] == 'Pair':
                    q = _t54[1]
                    r = _t54[2]
                    _t55 = r
                    if _t55[0] == 'Z0':
                        return ('Pair', opp(q), ('Z0',))
                    else:
                        return ('Pair', opp(add0(q)(('Zpos', ('XH',)))), add0(b)(r))
        elif _t52[0] == 'Zneg':
            a_prime = _t52[1]
            _t56 = b
            if _t56[0] == 'Z0':
                return ('Pair', ('Z0',), a)
            elif _t56[0] == 'Zpos':
                _t57 = pos_div_eucl(a_prime)(b)
                if _t57[0] == 'Pair':
                    q = _t57[1]
                    r = _t57[2]
                    _t58 = r
                    if _t58[0] == 'Z0':
                        return ('Pair', opp(q), ('Z0',))
                    else:
                        return ('Pair', opp(add0(q)(('Zpos', ('XH',)))), sub(b)(r))
            elif _t56[0] == 'Zneg':
                b_prime = _t56[1]
                _t59 = pos_div_eucl(a_prime)(('Zpos', b_prime))
                if _t59[0] == 'Pair':
                    q = _t59[1]
                    r = _t59[2]
                    return ('Pair', q, opp(r))
    return _k

def div(a):
    def _k(b):
        _t60 = div_eucl(a)(b)
        if _t60[0] == 'Pair':
            q = _t60[1]
            return q
    return _k

def modulo(a):
    def _k(b):
        _t61 = div_eucl(a)(b)
        if _t61[0] == 'Pair':
            r = _t61[2]
            return r
    return _k

def ediv(a):
    def _k(b):
        _t62 = ltb(('Z0',))(b)
        if _t62[0] == 'True':
            return div(a)(b)
        elif _t62[0] == 'False':
            return opp(div(a)(opp(b)))
    return _k

def emod(a):
    def _k(b):
        _t63 = ltb(('Z0',))(b)
        if _t63[0] == 'True':
            return modulo(a)(b)
        elif _t63[0] == 'False':
            return modulo(a)(opp(b))
    return _k

def pyfloordiv(a):
    def _k(b):
        _t64 = None
        _t65 = negb(eqb0(emod(a)(b))(('Z0',)))
        if _t65[0] == 'True':
            _t64 = ltb(b)(('Z0',))
        elif _t65[0] == 'False':
            _t64 = ('False',)
        _t66 = _t64
        if _t66[0] == 'True':
            return sub(ediv(a)(b))(('Zpos', ('XH',)))
        elif _t66[0] == 'False':
            return ediv(a)(b)
    return _k

def pymod(a):
    def _k(b):
        return sub(a)(mul0(pyfloordiv(a)(b))(b))
    return _k
