# Generated by proofs/json_to_python.py from a Rocq JSON extraction. Do not edit by hand.
# Every function below is the structural image of the verified MiniML source.

def compOpp(r):
    _t1 = r
    if _t1[0] == 'Eq':
        return ('Eq',)
    elif _t1[0] == 'Lt':
        return ('Gt',)
    elif _t1[0] == 'Gt':
        return ('Lt',)

def succ(x):
    _t2 = x
    if _t2[0] == 'XI':
        p = _t2[1]
        return ('XO', succ(p))
    elif _t2[0] == 'XO':
        p = _t2[1]
        return ('XI', p)
    elif _t2[0] == 'XH':
        return ('XO', ('XH',))

def add(x):
    def _k(y):
        _t3 = x
        if _t3[0] == 'XI':
            p = _t3[1]
            _t4 = y
            if _t4[0] == 'XI':
                q = _t4[1]
                return ('XO', add_carry(p)(q))
            elif _t4[0] == 'XO':
                q = _t4[1]
                return ('XI', add(p)(q))
            elif _t4[0] == 'XH':
                return ('XO', succ(p))
        elif _t3[0] == 'XO':
            p = _t3[1]
            _t5 = y
            if _t5[0] == 'XI':
                q = _t5[1]
                return ('XI', add(p)(q))
            elif _t5[0] == 'XO':
                q = _t5[1]
                return ('XO', add(p)(q))
            elif _t5[0] == 'XH':
                return ('XI', p)
        elif _t3[0] == 'XH':
            _t6 = y
            if _t6[0] == 'XI':
                q = _t6[1]
                return ('XO', succ(q))
            elif _t6[0] == 'XO':
                q = _t6[1]
                return ('XI', q)
            elif _t6[0] == 'XH':
                return ('XO', ('XH',))
    return _k

def add_carry(x):
    def _k(y):
        _t7 = x
        if _t7[0] == 'XI':
            p = _t7[1]
            _t8 = y
            if _t8[0] == 'XI':
                q = _t8[1]
                return ('XI', add_carry(p)(q))
            elif _t8[0] == 'XO':
                q = _t8[1]
                return ('XO', add_carry(p)(q))
            elif _t8[0] == 'XH':
                return ('XI', succ(p))
        elif _t7[0] == 'XO':
            p = _t7[1]
            _t9 = y
            if _t9[0] == 'XI':
                q = _t9[1]
                return ('XO', add_carry(p)(q))
            elif _t9[0] == 'XO':
                q = _t9[1]
                return ('XI', add(p)(q))
            elif _t9[0] == 'XH':
                return ('XO', succ(p))
        elif _t7[0] == 'XH':
            _t10 = y
            if _t10[0] == 'XI':
                q = _t10[1]
                return ('XI', succ(q))
            elif _t10[0] == 'XO':
                q = _t10[1]
                return ('XO', succ(q))
            elif _t10[0] == 'XH':
                return ('XI', ('XH',))
    return _k

def pred_double(x):
    _t11 = x
    if _t11[0] == 'XI':
        p = _t11[1]
        return ('XI', ('XO', p))
    elif _t11[0] == 'XO':
        p = _t11[1]
        return ('XI', pred_double(p))
    elif _t11[0] == 'XH':
        return ('XH',)

def mul(x):
    def _k(y):
        _t12 = x
        if _t12[0] == 'XI':
            p = _t12[1]
            return add(y)(('XO', mul(p)(y)))
        elif _t12[0] == 'XO':
            p = _t12[1]
            return ('XO', mul(p)(y))
        elif _t12[0] == 'XH':
            return y
    return _k

def compare_cont(r):
    def _k(x):
        def _k(y):
            _t13 = x
            if _t13[0] == 'XI':
                p = _t13[1]
                _t14 = y
                if _t14[0] == 'XI':
                    q = _t14[1]
                    return compare_cont(r)(p)(q)
                elif _t14[0] == 'XO':
                    q = _t14[1]
                    return compare_cont(('Gt',))(p)(q)
                elif _t14[0] == 'XH':
                    return ('Gt',)
            elif _t13[0] == 'XO':
                p = _t13[1]
                _t15 = y
                if _t15[0] == 'XI':
                    q = _t15[1]
                    return compare_cont(('Lt',))(p)(q)
                elif _t15[0] == 'XO':
                    q = _t15[1]
                    return compare_cont(r)(p)(q)
                elif _t15[0] == 'XH':
                    return ('Gt',)
            elif _t13[0] == 'XH':
                _t16 = y
                if _t16[0] == 'XH':
                    return r
                else:
                    return ('Lt',)
        return _k
    return _k

compare = compare_cont(('Eq',))

def double(x):
    _t17 = x
    if _t17[0] == 'Z0':
        return ('Z0',)
    elif _t17[0] == 'Zpos':
        p = _t17[1]
        return ('Zpos', ('XO', p))
    elif _t17[0] == 'Zneg':
        p = _t17[1]
        return ('Zneg', ('XO', p))

def succ_double(x):
    _t18 = x
    if _t18[0] == 'Z0':
        return ('Zpos', ('XH',))
    elif _t18[0] == 'Zpos':
        p = _t18[1]
        return ('Zpos', ('XI', p))
    elif _t18[0] == 'Zneg':
        p = _t18[1]
        return ('Zneg', pred_double(p))

def pred_double0(x):
    _t19 = x
    if _t19[0] == 'Z0':
        return ('Zneg', ('XH',))
    elif _t19[0] == 'Zpos':
        p = _t19[1]
        return ('Zpos', pred_double(p))
    elif _t19[0] == 'Zneg':
        p = _t19[1]
        return ('Zneg', ('XI', p))

def pos_sub(x):
    def _k(y):
        _t20 = x
        if _t20[0] == 'XI':
            p = _t20[1]
            _t21 = y
            if _t21[0] == 'XI':
                q = _t21[1]
                return double(pos_sub(p)(q))
            elif _t21[0] == 'XO':
                q = _t21[1]
                return succ_double(pos_sub(p)(q))
            elif _t21[0] == 'XH':
                return ('Zpos', ('XO', p))
        elif _t20[0] == 'XO':
            p = _t20[1]
            _t22 = y
            if _t22[0] == 'XI':
                q = _t22[1]
                return pred_double0(pos_sub(p)(q))
            elif _t22[0] == 'XO':
                q = _t22[1]
                return double(pos_sub(p)(q))
            elif _t22[0] == 'XH':
                return ('Zpos', pred_double(p))
        elif _t20[0] == 'XH':
            _t23 = y
            if _t23[0] == 'XI':
                q = _t23[1]
                return ('Zneg', ('XO', q))
            elif _t23[0] == 'XO':
                q = _t23[1]
                return ('Zneg', pred_double(q))
            elif _t23[0] == 'XH':
                return ('Z0',)
    return _k

def add0(x):
    def _k(y):
        _t24 = x
        if _t24[0] == 'Z0':
            return y
        elif _t24[0] == 'Zpos':
            x_prime = _t24[1]
            _t25 = y
            if _t25[0] == 'Z0':
                return x
            elif _t25[0] == 'Zpos':
                y_prime = _t25[1]
                return ('Zpos', add(x_prime)(y_prime))
            elif _t25[0] == 'Zneg':
                y_prime = _t25[1]
                return pos_sub(x_prime)(y_prime)
        elif _t24[0] == 'Zneg':
            x_prime = _t24[1]
            _t26 = y
            if _t26[0] == 'Z0':
                return x
            elif _t26[0] == 'Zpos':
                y_prime = _t26[1]
                return pos_sub(y_prime)(x_prime)
            elif _t26[0] == 'Zneg':
                y_prime = _t26[1]
                return ('Zneg', add(x_prime)(y_prime))
    return _k

def opp(x):
    _t27 = x
    if _t27[0] == 'Z0':
        return ('Z0',)
    elif _t27[0] == 'Zpos':
        x0 = _t27[1]
        return ('Zneg', x0)
    elif _t27[0] == 'Zneg':
        x0 = _t27[1]
        return ('Zpos', x0)

def sub(m):
    def _k(n):
        return add0(m)(opp(n))
    return _k

def mul0(x):
    def _k(y):
        _t28 = x
        if _t28[0] == 'Z0':
            return ('Z0',)
        elif _t28[0] == 'Zpos':
            x_prime = _t28[1]
            _t29 = y
            if _t29[0] == 'Z0':
                return ('Z0',)
            elif _t29[0] == 'Zpos':
                y_prime = _t29[1]
                return ('Zpos', mul(x_prime)(y_prime))
            elif _t29[0] == 'Zneg':
                y_prime = _t29[1]
                return ('Zneg', mul(x_prime)(y_prime))
        elif _t28[0] == 'Zneg':
            x_prime = _t28[1]
            _t30 = y
            if _t30[0] == 'Z0':
                return ('Z0',)
            elif _t30[0] == 'Zpos':
                y_prime = _t30[1]
                return ('Zneg', mul(x_prime)(y_prime))
            elif _t30[0] == 'Zneg':
                y_prime = _t30[1]
                return ('Zpos', mul(x_prime)(y_prime))
    return _k

def compare0(x):
    def _k(y):
        _t31 = x
        if _t31[0] == 'Z0':
            _t32 = y
            if _t32[0] == 'Z0':
                return ('Eq',)
            elif _t32[0] == 'Zpos':
                return ('Lt',)
            elif _t32[0] == 'Zneg':
                return ('Gt',)
        elif _t31[0] == 'Zpos':
            x_prime = _t31[1]
            _t33 = y
            if _t33[0] == 'Zpos':
                y_prime = _t33[1]
                return compare(x_prime)(y_prime)
            else:
                return ('Gt',)
        elif _t31[0] == 'Zneg':
            x_prime = _t31[1]
            _t34 = y
            if _t34[0] == 'Zneg':
                y_prime = _t34[1]
                return compOpp(compare(x_prime)(y_prime))
            else:
                return ('Lt',)
    return _k

def leb(x):
    def _k(y):
        _t35 = compare0(x)(y)
        if _t35[0] == 'Gt':
            return ('False',)
        else:
            return ('True',)
    return _k

def max(n):
    def _k(m):
        _t36 = compare0(n)(m)
        if _t36[0] == 'Lt':
            return m
        else:
            return n
    return _k

def min(n):
    def _k(m):
        _t37 = compare0(n)(m)
        if _t37[0] == 'Gt':
            return m
        else:
            return n
    return _k

def widenL(ol):
    def _k(nl):
        _t38 = ol
        if _t38[0] == 'Some':
            o = _t38[1]
            _t39 = nl
            if _t39[0] == 'Some':
                n = _t39[1]
                _t40 = leb(o)(n)
                if _t40[0] == 'True':
                    return ('Some', o)
                elif _t40[0] == 'False':
                    return ('None',)
            elif _t39[0] == 'None':
                return ('None',)
        elif _t38[0] == 'None':
            return ('None',)
    return _k

def widenU(ou):
    def _k(nu):
        _t41 = ou
        if _t41[0] == 'Some':
            o = _t41[1]
            _t42 = nu
            if _t42[0] == 'Some':
                n = _t42[1]
                _t43 = leb(n)(o)
                if _t43[0] == 'True':
                    return ('Some', o)
                elif _t43[0] == 'False':
                    return ('None',)
            elif _t42[0] == 'None':
                return ('None',)
        elif _t41[0] == 'None':
            return ('None',)
    return _k

def iadd(a):
    def _k(b):
        def _k(c):
            def _k(d):
                return ('Pair', add0(a)(c), add0(b)(d))
            return _k
        return _k
    return _k

def ineg(a):
    def _k(b):
        return ('Pair', opp(b), opp(a))
    return _k

def isub(a):
    def _k(b):
        def _k(c):
            def _k(d):
                return ('Pair', sub(a)(d), sub(b)(c))
            return _k
        return _k
    return _k

def ijoin(a):
    def _k(b):
        def _k(c):
            def _k(d):
                return ('Pair', min(a)(c), max(b)(d))
            return _k
        return _k
    return _k

def imul(al):
    def _k(ah):
        def _k(bl):
            def _k(bh):
                return ('Pair', min(min(mul0(al)(bl))(mul0(al)(bh)))(min(mul0(ah)(bl))(mul0(ah)(bh))), max(max(mul0(al)(bl))(mul0(al)(bh)))(max(mul0(ah)(bl))(mul0(ah)(bh))))
            return _k
        return _k
    return _k
