# Generated by proofs/json_to_python.py from a Rocq JSON extraction. Do not edit by hand.
# Every function below is the structural image of the verified MiniML source.

def fst(p):
    _t1 = p
    if _t1[0] == '(,)':
        x = _t1[1]
        return x

def snd(p):
    _t2 = p
    if _t2[0] == '(,)':
        y = _t2[2]
        return y

def app(l):
    def _k(m):
        _t3 = l
        if _t3[0] == '[]':
            return m
        elif _t3[0] == '(::)':
            a = _t3[1]
            l1 = _t3[2]
            return ('(::)', a, app(l1)(m))
    return _k

def eqb(n):
    def _k(m):
        _t4 = n
        if _t4[0] == 'O':
            _t5 = m
            if _t5[0] == 'O':
                return ('True',)
            elif _t5[0] == 'S':
                return ('False',)
        elif _t4[0] == 'S':
            n_prime = _t4[1]
            _t6 = m
            if _t6[0] == 'O':
                return ('False',)
            elif _t6[0] == 'S':
                m_prime = _t6[1]
                return eqb(n_prime)(m_prime)
    return _k

def subst_expr(x):
    def _k(e):
        def _k(t):
            _t7 = t
            if _t7[0] == 'EVar':
                y = _t7[1]
                _t8 = eqb(x)(y)
                if _t8[0] == 'True':
                    return e
                elif _t8[0] == 'False':
                    return ('EVar', y)
            elif _t7[0] == 'EConst':
                z0 = _t7[1]
                return ('EConst', z0)
            elif _t7[0] == 'EAdd':
                a = _t7[1]
                b = _t7[2]
                return ('EAdd', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'ESub':
                a = _t7[1]
                b = _t7[2]
                return ('ESub', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'EMul':
                a = _t7[1]
                b = _t7[2]
                return ('EMul', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'EDiv':
                a = _t7[1]
                b = _t7[2]
                return ('EDiv', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'EMod':
                a = _t7[1]
                b = _t7[2]
                return ('EMod', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'ELt':
                a = _t7[1]
                b = _t7[2]
                return ('ELt', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'ELe':
                a = _t7[1]
                b = _t7[2]
                return ('ELe', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'EEq':
                a = _t7[1]
                b = _t7[2]
                return ('EEq', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'ENot':
                a = _t7[1]
                return ('ENot', subst_expr(x)(e)(a))
            elif _t7[0] == 'EAnd':
                a = _t7[1]
                b = _t7[2]
                return ('EAnd', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t7[0] == 'EOr':
                a = _t7[1]
                b = _t7[2]
                return ('EOr', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
        return _k
    return _k

def subst_form(x):
    def _k(e):
        def _k(f):
            _t9 = f
            if _t9[0] == 'FLt':
                a = _t9[1]
                b = _t9[2]
                return ('FLt', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t9[0] == 'FLe':
                a = _t9[1]
                b = _t9[2]
                return ('FLe', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t9[0] == 'FEq':
                a = _t9[1]
                b = _t9[2]
                return ('FEq', subst_expr(x)(e)(a), subst_expr(x)(e)(b))
            elif _t9[0] == 'FNot':
                g = _t9[1]
                return ('FNot', subst_form(x)(e)(g))
            elif _t9[0] == 'FAnd':
                g = _t9[1]
                h = _t9[2]
                return ('FAnd', subst_form(x)(e)(g), subst_form(x)(e)(h))
            elif _t9[0] == 'FOr':
                g = _t9[1]
                h = _t9[2]
                return ('FOr', subst_form(x)(e)(g), subst_form(x)(e)(h))
            elif _t9[0] == 'FImpl':
                g = _t9[1]
                h = _t9[2]
                return ('FImpl', subst_form(x)(e)(g), subst_form(x)(e)(h))
            else:
                x0 = _t9
                return x0
        return _k
    return _k

def defined_expr(t):
    _t10 = t
    if _t10[0] == 'EAdd':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'ESub':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'EMul':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'EDiv':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), ('FAnd', defined_expr(b), ('FNot', ('FEq', b, ('EConst', ('Z0',))))))
    elif _t10[0] == 'EMod':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), ('FAnd', defined_expr(b), ('FNot', ('FEq', b, ('EConst', ('Z0',))))))
    elif _t10[0] == 'ELt':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'ELe':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'EEq':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'ENot':
        a = _t10[1]
        return defined_expr(a)
    elif _t10[0] == 'EAnd':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    elif _t10[0] == 'EOr':
        a = _t10[1]
        b = _t10[2]
        return ('FAnd', defined_expr(a), defined_expr(b))
    else:
        return ('FTrue',)

def wpg(p):
    def _k(q):
        _t11 = p
        if _t11[0] == 'PNil':
            return q
        elif _t11[0] == 'PAsgn':
            x = _t11[1]
            e = _t11[2]
            rest = _t11[3]
            return ('FAnd', defined_expr(e), subst_form(x)(e)(wpg(rest)(q)))
        elif _t11[0] == 'PCond':
            c = _t11[1]
            thn = _t11[2]
            els = _t11[3]
            rest = _t11[4]
            return ('FAnd', defined_expr(c), ('FAnd', ('FImpl', ('FNot', ('FEq', c, ('EConst', ('Z0',)))), wpg(thn)(wpg(rest)(q))), ('FImpl', ('FEq', c, ('EConst', ('Z0',))), wpg(els)(wpg(rest)(q)))))
    return _k

def vcg(k):
    def _k(q):
        _t12 = k
        if _t12[0] == 'KSkip':
            return ('(,)', q, ('[]',))
        elif _t12[0] == 'KAsgn':
            x = _t12[1]
            e = _t12[2]
            return ('(,)', ('FAnd', defined_expr(e), subst_form(x)(e)(q)), ('[]',))
        elif _t12[0] == 'KSeq':
            a = _t12[1]
            b = _t12[2]
            return ('(,)', fst(vcg(a)(fst(vcg(b)(q)))), app(snd(vcg(a)(fst(vcg(b)(q)))))(snd(vcg(b)(q))))
        elif _t12[0] == 'KIf':
            c = _t12[1]
            t = _t12[2]
            e = _t12[3]
            return ('(,)', ('FAnd', defined_expr(c), ('FAnd', ('FImpl', ('FNot', ('FEq', c, ('EConst', ('Z0',)))), fst(vcg(t)(q))), ('FImpl', ('FEq', c, ('EConst', ('Z0',))), fst(vcg(e)(q))))), app(snd(vcg(t)(q)))(snd(vcg(e)(q))))
        elif _t12[0] == 'KWhile':
            inv = _t12[1]
            c = _t12[2]
            body = _t12[3]
            return ('(,)', inv, ('(::)', ('FImpl', inv, defined_expr(c)), ('(::)', ('FImpl', ('FAnd', inv, ('FNot', ('FEq', c, ('EConst', ('Z0',))))), fst(vcg(body)(inv))), ('(::)', ('FImpl', ('FAnd', inv, ('FEq', c, ('EConst', ('Z0',)))), q), snd(vcg(body)(inv))))))
    return _k
