#!/usr/bin/env bash
# Certificate-checking gate. touchstone_smtcoq.v closes every goal by re-checking an external SMT
# solver's proof certificate inside Coq's kernel (SMTCoq), so a PROVED integer obligation ships a
# kernel-validated certificate rather than resting on the solver's word. It runs wherever the SMTCoq
# toolchain is reachable from the ambient `coqc` (Coq 8.20.1 + coq-smtcoq 2.3+8.20) with veriT
# (stable2016) or cvc4 1.6 on PATH; proofs/Dockerfile.smtcoq provisions exactly that and the smtcoq CI
# job runs it non-skipped. It SKIPS (exit 0) only when SMTCoq is not importable -- e.g. under the
# Rocq 9.0 switch the other companion files use -- so the main gate degrades gracefully.
set -uo pipefail

# veriT / cvc4 may live on PATH or in a conventional local bin
command -v veriT >/dev/null 2>&1 || command -v cvc4 >/dev/null 2>&1 \
  || export PATH="$HOME/smtsolvers:$HOME/.local/bin:$PATH"

# Probe: can the ambient coqc load SMTCoq? (Fails fast under Rocq 9.0 / when SMTCoq is absent.)
probe_dir="$(mktemp -d)"; printf 'From SMTCoq Require Import SMTCoq.\n' > "${probe_dir}/probe.v"
if ! coqc "${probe_dir}/probe.v" >/dev/null 2>&1; then
  rm -rf "${probe_dir}"
  echo "=== touchstone_smtcoq.v === SKIPPED (SMTCoq not available to coqc)"; exit 0
fi
rm -rf "${probe_dir}"
if ! command -v veriT >/dev/null 2>&1 && ! command -v cvc4 >/dev/null 2>&1; then
  echo "=== touchstone_smtcoq.v === SKIPPED (no veriT / cvc4 on PATH)"; exit 0
fi

if [ ! -f sat.plf ]; then                       # stage SMTCoq's LFSC signatures next to the proof
  pfx="$(opam var prefix 2>/dev/null || true)"
  sig="$(find "${pfx}/.opam-switch/sources" -name sat.plf -path '*signatures*' 2>/dev/null | head -1)"
  [ -n "${sig}" ] && cp "$(dirname "${sig}")"/*.plf . 2>/dev/null || true
fi

if coqc touchstone_smtcoq.v >/tmp/smtcoq_out 2>&1; then
  echo "=== touchstone_smtcoq.v === certificate-checked in Coq's kernel (SMTCoq + veriT/cvc4)"
else
  echo "=== touchstone_smtcoq.v === FAILED"; tail -8 /tmp/smtcoq_out; exit 1
fi

# touchstone_obligations.v holds the engine's ACTUAL integer obligations (generated by
# touchstone.smtcoq_export); each is re-checked from its veriT certificate in Coq's kernel.
if [ -f touchstone_obligations.v ]; then
  if coqc touchstone_obligations.v >/tmp/oblig_out 2>&1; then
    echo "=== touchstone_obligations.v === engine obligations certificate-checked in Coq's kernel"
  else
    echo "=== touchstone_obligations.v === FAILED"; tail -12 /tmp/oblig_out; exit 1
  fi
fi
